### ISSUE TITLE
Why can not I cancel the order?

### ISSUE THREAD

**Issue by hiquanta** [xeroc/python-bitshares#18]
This is my code：
market = Market("BTS:CNY")
account = Account("bitshares.bot")

market.bitshares.wallet.unlock("xxxxxx")
s = account.openorders.__getitem__(0).get("id")
print(s.split('.')[2])

print(market.cancel(s.split('.')[2]))
This is the logs:
30995418
Traceback (most recent call last):
  File "/home/hiquanta/PycharmProjects/btsbots/Trans.py", line 37, in <module>
    print(market.cancel(s))
  File "/home/hiquanta/.pyenv/versions/3.6.2/lib/python3.6/site-packages/bitshares/market.py", line 545, in cancel
    return self.bitshares.cancel(orderNumber, account=account)
  File "/home/hiquanta/.pyenv/versions/3.6.2/lib/python3.6/site-packages/bitshares/bitshares.py", line 862, in cancel
    "prefix": self.rpc.chain_params["prefix"]}))
  File "/home/hiquanta/.pyenv/versions/3.6.2/lib/python3.6/site-packages/bitsharesbase/operations.py", line 196, in __init__
    ('order', ObjectId(kwargs["order"], "limit_order")),
  File "/home/hiquanta/.pyenv/versions/3.6.2/lib/python3.6/site-packages/bitsharesbase/objects.py", line 36, in __init__
    raise Exception("Object id is invalid")
Exception: Object id is invalid

**Comment by hiquanta** [comment]
I‘m wrong ，I know why！
z=market.accountopenorders(account).__getitem__(0)
market.cancel([z["id"]],account=account)

**Comment by xeroc** [comment]
You can also use 
    market.accountopenorders(account)[0]

Reason is that an account can have multiple orders open in one market

**Comment by Daice** [comment]
`>>> market.accountopenorders(account)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daiz/Document/python-bitshares/bitshares/market.py", line 340, in accountopenorders
    orders = account["limit_orders"]
  File "/home/daiz/Document/python-bitshares/bitshares/blockchainobject.py", line 153, in __getitem__
    return super().__getitem__(key)
KeyError: 'limit_orders'`
