### ISSUE TITLE
How to limit node reconnect attempts?

### ISSUE THREAD

**Issue by grctest** [xeroc/python-bitshares#37]
I'm trying to provide redundent node connections when publishing price feeds for long periods of time.

When I try the following it gets stuck in a reconnect loop for the fist invalid server. Is there a way of providing a timeout of a max connect attempts, so that I can loop through a list of API servers?

```
full_node_list = ["wss://bitshfares.openledger.info/ws",
                         "wss://bitshares.crypto.fans/ws",
                         "wss://openledger.hk/ws"]

for server in full_node_list:
  try:
    bitshares_api_node = BitShares(server)
    break
  except:
    print(server + " is offline!")
```

Output:
```
Lost connection to node during wsconnect(): wss://nodfe.bitshares.eu/ws (2/-1) Retrying in 2 seconds
Lost connection to node during wsconnect(): wss://nodfe.bitshares.eu/ws (3/-1) Retrying in 4 seconds
Lost connection to node during wsconnect(): wss://nodfe.bitshares.eu/ws (4/-1) Retrying in 6 seconds
......
```

Should I instead try to connect using a 3rd party websocket client to ping the API servers before moving ahead with creating a Bitshares instance?

Cheers

**Comment by grctest** [comment]
I threw together a chunk of Python code that checks the status of full node API servers prior to attempting any python-bitshares Bitshares() fullnode connections using Lomond:

```
import wsaccel
from lomond.websocket import WebSocket

if __name__ == "__main__":

    full_node_list = ["wss://node.bitdashares.eu/ws",
                      "wss://dexnfffode.net/ws",
                      "wss://bitshares.openledger.info/ws",
                      "wss://bitshares.crypto.fans/ws",
                      "wss://openledger.hk/ws"]

    online_server = ""
    
    for server in full_node_list:
      if (online_server == ""):
          try:
            ws = WebSocket(server)
            for event in ws.connect():
                print(event.name)
                if event.name == "connect_fail":
                    print(server + " is offline!")
                    break
                if event.name == "connecting":
                    continue
                if event.name == "connected":
                    continue
                if event.name == "ready":
                    online_server = server
                    print(server + " is online!")
                    ws.close()
                    break
          except:
            print(server + " is offline!")

    print("The online server is: {}".format(online_server))
```

Some error handling or max limit on wsconnect() attempts would still be a great redundancy step, perhaps a node could go down during script execution after having successfully checked it using the above script?

**Comment by grctest** [comment]
Very strange new error related to websockets, any idea how to solve this?

```
Traceback (most recent call last):
  File "feed.py", line 72, in <module>
    bitshares_api_node = BitShares("wss://bitshares.crypto.fans/ws")
  File "/home/btsapi/python-bitshares/bitshares/bitshares.py", line 151, in __init__
    **kwargs)
  File "/home/btsapi/python-bitshares/bitshares/bitshares.py", line 180, in connect
    self.rpc = BitSharesNodeRPC(node, rpcuser, rpcpassword, **kwargs)
  File "/home/btsapi/python-bitshares/bitsharesapi/bitsharesnoderpc.py", line 23, in __init__
    super(BitSharesNodeRPC, self).__init__(*args, **kwargs)
  File "/home/btsapi/HUG/lib/python3.6/site-packages/grapheneapi/graphenewsrpc.py", line 64, in __init__
    self.wsconnect()
  File "/home/btsapi/HUG/lib/python3.6/site-packages/grapheneapi/graphenewsrpc.py", line 79, in wsconnect
    self.ws = websocket.WebSocket(sslopt=sslopt_ca_certs)
TypeError: __init__() got an unexpected keyword argument 'sslopt'

```

**Comment by grctest** [comment]
Ran into the wsconnect retry loop after pre-checking the API node was up, need an additional/alternative solution..

**Comment by xeroc** [comment]
`BitShares()` consumes a list of nodes too and cycles thru them

```
    full_node_list = ["wss://node.bitdashares.eu/ws",
                      "wss://dexnfffode.net/ws",
                      "wss://bitshares.openledger.info/ws",
                      "wss://bitshares.crypto.fans/ws",
                      "wss://openledger.hk/ws"]

    bts = BitShares(full_node_list)
```
