### ISSUE TITLE
Attempts to get txId via Signed_Transaction.id for a transaction with operation expiration field set way in the past cause an exception

### ISSUE THREAD

**Issue by DEEXPrivate** [xeroc/python-bitshares#54]
Example code:
```python
from bitshares.block import Block
from bitsharesbase.signedtransactions import Signed_Transaction
from pprint import pprint
block = Block(25065606)
pprint( block['transactions'][8] )
Signed_Transaction(**block['transactions'][8]).id

```
Output:
```python
{'expiration': '2018-03-09T03:11:50',
 'extensions': [],
 'operation_results': [[1, '1.7.58254444']],
 'operations': [[1,
                 {'amount_to_sell': {'amount': 100000000,
                                     'asset_id': '1.3.113'},
                  'expiration': '1963-11-29T12:38:45',
                  'extensions': [],
                  'fee': {'amount': 92, 'asset_id': '1.3.0'},
                  'fill_or_kill': False,
                  'min_to_receive': {'amount': 15847860, 'asset_id': '1.3.121'},
                  'seller': '1.2.33015'}]],
 'ref_block_num': 30853,
 'ref_block_prefix': 594311437,
 'signatures': ['204fb2556eced197d849f87618683f4a3ab2c560b59bae6adecad3bd887adf959d45262d6d74123c933321898176ff7f062c96f88c94b16fac4358d694959b46fe']}
```
```
Traceback (most recent call last):
  File "bug.py", line 6, in <module>
    Signed_Transaction(**block['transactions'][8]).id
  File "/home/femtocat/.local/lib/python3.5/site-packages/graphenebase/signedtransactions.py", line 84, in id
    h = hashlib.sha256(bytes(self)).digest()
  File "/home/femtocat/.local/lib/python3.5/site-packages/graphenebase/objects.py", line 84, in __bytes__
    b += bytes(value)
  File "/home/femtocat/.local/lib/python3.5/site-packages/graphenebase/types.py", line 197, in __bytes__
    return bytes(self.length) + b"".join([bytes(a) for a in self.data])
  File "/home/femtocat/.local/lib/python3.5/site-packages/graphenebase/types.py", line 197, in <listcomp>
    return bytes(self.length) + b"".join([bytes(a) for a in self.data])
  File "/home/femtocat/.local/lib/python3.5/site-packages/graphenebase/objects.py", line 57, in __bytes__
    return bytes(Id(self.opId)) + bytes(self.op)
  File "/home/femtocat/.local/lib/python3.5/site-packages/graphenebase/objects.py", line 84, in __bytes__
    b += bytes(value)
  File "/home/femtocat/.local/lib/python3.5/site-packages/graphenebase/types.py", line 214, in __bytes__
    return struct.pack("<I", timegm(time.strptime((self.data + "UTC"), timeformat)))
struct.error: argument out of range
```

**Comment by xeroc** [comment]
Known issue. Any datetime that is before epoch 0 (1990) will result in an exception
